#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Concert2Go.Resource", IsApplication=true)]

namespace Concert2Go
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int genre_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Background3 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Concert2Go = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int monoandroidsplash = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070004
			public const int ArtiestTekst = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int DatumTekst = 2131165194;
			
			// aapt resource value: 0x7f070005
			public const int LandTekst = 2131165189;
			
			// aapt resource value: 0x7f07000b
			public const int OpmerkingTekst = 2131165195;
			
			// aapt resource value: 0x7f070006
			public const int PlaatsTekst = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int SpinnerMuzieksoort = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int ZaalTekst = 2131165191;
			
			// aapt resource value: 0x7f07000c
			public const int btnSave = 2131165196;
			
			// aapt resource value: 0x7f070000
			public const int imageView1 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int linearLayout1 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int lvConcerten = 2131165187;
			
			// aapt resource value: 0x7f070009
			public const int pickDate = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int txtZoeken = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Overzicht = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Toevoegen = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int genre_prompt = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int menuitem1 = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
